/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp._certcenter64._inica70;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.util.Date.*;
import java.util.Calendar.*;
import java.text.SimpleDateFormat;
import java.text.DecimalFormat;
import java.lang.*;
import java.lang.String.*;
import java.text.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public class _excelDown__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  public static int getDateDiff(String startDate, String endDate) {
  
  	startDate = startDate.substring(0,10).replace("-","")+"000000";
  	endDate = endDate.substring(0,10).replace("-","")+"000000";
  	long diffMillis = 0l;
  	int diff = 0;	
  	try{
  		java.util.Date endDay = new SimpleDateFormat("yyyyMMddHHmmss").parse(endDate);
  		Calendar endDayCal = new GregorianCalendar();
  		endDayCal.setTime(endDay);
  	 
  		java.util.Date startDay = new SimpleDateFormat("yyyyMMddHHmmss").parse(startDate);
  		Calendar startDayCal = new GregorianCalendar();
  		startDayCal.setTime(startDay);
  		 
  		diffMillis = endDayCal.getTimeInMillis() - startDayCal.getTimeInMillis();
  		
  		diff = (int) (diffMillis/ (24 * 60 * 60 * 1000));
  	}catch(Exception e)    {
  		e.printStackTrace(System.out);
  	}
  	
  	return diff;
  
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("application/vnd.ms-excel;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
//************************************************
//      \uad00\ub9ac\uc790 \uc138\uc158 \uccb4\ud06c
//************************************************
String adminLogin = (String)session.getAttribute("adminLogin");
if (adminLogin == null) {
	response.setCharacterEncoding("EUC-KR");
	PrintWriter writer = response.getWriter();
	writer.println("<script type='text/javascript'>");
	writer.println("alert('\uad00\ub9ac\uc790 \ub85c\uadf8\uc778 \uc815\ubcf4\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.');");
	writer.println("parent.location.href='ini_manage_cert_login.jsp'");
	writer.println("</script>");
	writer.flush();
	return;
}


String fileName="" ;





int totalRecord = 0; //\ucd1d \ub370\uc774\ud130 \uac1c\uc218\ub97c \uc800\uc7a5\ud560 \ubcc0\uc218
int totalPage = 0;  //\ucd1d \ud398\uc774\uc9c0\uc218\ub97c \uc800\uc7a5\ud560 \ubcc0\uc218



//************************************************
//     \ud398\uc774\uc9c0 \ubcc0\uc218 \uc120\uc5b8 End
//************************************************

//\uac80\uc0c9\uc870\uac74
//String m_searchGb = null ; //\uae30\ubcf8 \uac80\uc0c9\uae30\uac04\uc740 \uae08\uc77c
//m_searchGb = m_IP.getParameter("searchGb");
String m_searchGb = request.getParameter("searchGb");

if (m_searchGb == null || m_searchGb.equals("")) {
	m_searchGb = "T";
}
String f_yyyy = request.getParameter("f_yyyy"); 
String f_mm = request.getParameter("f_mm"); 
String f_dd = request.getParameter("f_dd"); 
String t_yyyy = request.getParameter("t_yyyy"); 
String t_mm = request.getParameter("t_mm"); 
String t_dd = request.getParameter("t_dd");
String STATUS = request.getParameter("STATUS");
if (STATUS == null || STATUS.equals("")) {
	STATUS = "I";
}
String gb = request.getParameter("gb");
if (gb == null || gb.equals("")) {
	gb = "C.USERNAME";
}
String strKeyword = request.getParameter("strKeyword");
if (strKeyword == null || strKeyword.equals("") || strKeyword.equals("null")) {
	strKeyword = "";
}

DecimalFormat df = new DecimalFormat("00");
Calendar now = Calendar.getInstance();
String nowYear = String.valueOf(now.get(Calendar.YEAR));
String nowMonth = String.valueOf(now.get(Calendar.MONTH)+1);
String nowDay = String.valueOf(now.get(Calendar.DATE));


String hour = ""; //\uc2dc\uac04\uc744 \uad6c\ud55c\ub2e4
if( now.get(Calendar.AM_PM) == Calendar.PM){
  hour = df.format(now.get(Calendar.HOUR)+12); //Calendar.PM\uc774\uba74 12\ub97c \ub354\ud55c\ub2e4
} else {
  hour = df.format(now.get(Calendar.HOUR));
}

String minute = df.format(now.get(Calendar.MINUTE)); //\ubd84\uc744 \uad6c\ud55c\ub2e4
String second = df.format(now.get(Calendar.SECOND)); //\ucd08\ub97c \uad6c\ud55c\ub2e4


if (f_yyyy == null || f_yyyy.equals("") || t_yyyy == null || t_yyyy.equals("") ) {
	f_yyyy = nowYear ;
	t_yyyy = nowYear ;
}
if (f_mm == null || f_mm.equals("") || t_mm == null || t_mm.equals("") ) {
	if (nowMonth.length() < 2 ) {
		f_mm = "0" + nowMonth ;
		t_mm = "0" + nowMonth ;
	}else{
		f_mm = nowMonth ;
		t_mm = nowMonth ;
	}
}

if (f_dd == null || f_dd.equals("") || t_dd == null || t_dd.equals("") ) {
	if (nowDay.length() < 2 ) {
		f_dd = "0" + nowDay ;
		t_dd = "0" + nowDay ;
	}else{
		f_dd = nowDay ;
		t_dd = nowDay ;
	}
}


String CurYYYMMDDHHMMSS = nowYear + nowMonth + nowDay + hour + minute + second ;

String CurTime = nowYear+"\ub144 " + nowMonth +"\uc6d4 " + nowDay + "\uc77c " + hour + ":" + minute +":" + second ;


String baseDatCol = "A.ISSUE_DATE";
String baseCondQuery = "" ;
if (m_searchGb.equals("T")) { //\uae08\uc77c
	baseCondQuery = " AND to_char("+ baseDatCol +",'YYYY-MM-DD') = to_char(sysdate,'YYYY-MM-DD') ";
	fileName = fileName + "\uae08\uc77c\ubc1c\uae09\ub0b4\uc5ed";
}
else if (m_searchGb.equals("Y")) { //\uc5b4\uc81c
	baseCondQuery = " AND to_char("+ baseDatCol +",'YYYY-MM-DD') = to_char(sysdate-1,'YYYY-MM-DD') ";
	fileName = fileName + "\uc5b4\uc81c\ubc1c\uae09\ub0b4\uc5ed";
}
else if (m_searchGb.equals("TM")) { //\uc774\ubc88\ub2ec	
	baseCondQuery = " AND to_char("+ baseDatCol +",'YYYY-MM-DD') between to_char(sysdate,'YYYY-MM') || '-01' And    to_char("+ baseDatCol +",'YYYY-MM-DD')";
	fileName = fileName + "\uc774\ubc88\ub2ec\ubc1c\uae09\ub0b4\uc5ed";
}
else if (m_searchGb.equals("M1")) { //1\uac1c\uc6d4
	baseCondQuery = " AND  to_char("+ baseDatCol +",'YYYY-MM-DD') between to_char(sysdate-30,'YYYY-MM-DD') And    to_char("+ baseDatCol +",'YYYY-MM-DD') ";
	fileName = fileName + "1\uac1c\uc6d4\uac04\uc758\ubc1c\uae09\ub0b4\uc5ed";
}
else if (m_searchGb.equals("M3")) { //3\uac1c\uc6d4
	baseCondQuery = " AND  to_char("+ baseDatCol +",'YYYY-MM-DD') between to_char(sysdate-90,'YYYY-MM-DD') And    to_char("+ baseDatCol +",'YYYY-MM-DD') ";
	fileName = fileName + "3\uac1c\uc6d4\uac04\uc758\ubc1c\uae09\ub0b4\uc5ed";
}
else if (m_searchGb.equals("B")) { //\uae30\uac04\ubcc4
	baseCondQuery = " AND  to_char("+ baseDatCol +",'YYYY-MM-DD') between to_char('"+ f_yyyy +"-"+f_mm+"-"+f_dd +"') And    to_char('"+ t_yyyy +"-"+t_mm+"-"+t_dd +"') ";
	fileName = fileName + "\uae30\uac04\ubcc4\ubc1c\uae09\ub0b4\uc5ed("+f_yyyy+"."+f_mm+"."+f_dd+"_"+t_yyyy+"."+t_mm+"."+t_dd+")";
}
else{
	baseCondQuery = " AND to_char("+ baseDatCol +",'YYYY-MM-DD') = to_char(sysdate,'YYYY-MM-DD') ";
	fileName = fileName + "\uae08\uc77c\ubc1c\uae09\ub0b4\uc5ed";
}
//\uc720\ud6a8(I) / \ud3d0\uae30(R)
if (STATUS.equals("I") || STATUS.equals("R")){
	baseCondQuery = baseCondQuery + " AND  A.STATUS = '"+ STATUS +"' ";
}
if (STATUS.equals("I")){
	fileName = fileName + "_\uc720\ud6a8\uc778\uc99d\uc11c";
}else if (STATUS.equals("R")){
	fileName = fileName + "_\ud3d0\uae30\uc778\uc99d\uc11c";
}else{
	fileName = fileName + "_\uc804\uccb4";
}

fileName = fileName ;//+ "_" + CurYYYMMDDHHMMSS ;

Context icu = new InitialContext();
DataSource dsu = (DataSource) icu.lookup("java:comp/env/jdbc/INICA");
ResultSet rsu = null;

Connection connu = null;
Statement stmtu = null;
PreparedStatement pstmtu = null;



String strTotQuerey = "" ;
strTotQuerey = strTotQuerey + "SELECT COUNT(*) AS CNT " ;
strTotQuerey = strTotQuerey + "FROM ( " ;

strTotQuerey = strTotQuerey + "SELECT " ;
strTotQuerey = strTotQuerey + "        A.SERIAL " ;
strTotQuerey = strTotQuerey + "    ,   A.USERID " ;
strTotQuerey = strTotQuerey + "    ,   ( " ;
strTotQuerey = strTotQuerey + "			SELECT DISTINCT(nvl(USERNAME,'TEST\uc0ac\uc6a9\uc790'))  " ;
strTotQuerey = strTotQuerey + "			FROM USER_PWD  " ;
strTotQuerey = strTotQuerey + "			WHERE USERID=A.USERID " ;
strTotQuerey = strTotQuerey + "			) AS USERNAME " ;
strTotQuerey = strTotQuerey + "    ,   ( " ;
strTotQuerey = strTotQuerey + "			SELECT NVL(USERIP,'&nbsp;')   " ;
strTotQuerey = strTotQuerey + "			FROM USER_PWD  " ;
strTotQuerey = strTotQuerey + "			WHERE USERID=A.USERID " ;
strTotQuerey = strTotQuerey + "			) AS USERIP " ;
strTotQuerey = strTotQuerey + "    ,   A.ISSUER_CODE " ;
strTotQuerey = strTotQuerey + "    ,   A.STATUS " ;
strTotQuerey = strTotQuerey + "    ,  ( " ;
strTotQuerey = strTotQuerey + "          CASE A.STATUS " ;
strTotQuerey = strTotQuerey + "              WHEN 'I' THEN '\uc720\ud6a8' " ;
strTotQuerey = strTotQuerey + "              WHEN 'R' THEN '\ud398\uae30' " ;
strTotQuerey = strTotQuerey + "              WHEN 'S' THEN '\ud6a8\ub825\uc815\uc9c0' " ;
strTotQuerey = strTotQuerey + "              ELSE '\uc720\ud6a8' " ;
strTotQuerey = strTotQuerey + "          END " ;
strTotQuerey = strTotQuerey + "        ) AS STATUSNM " ;
strTotQuerey = strTotQuerey + "   ,  ( " ;
strTotQuerey = strTotQuerey + "        CASE A.LASTSTATUS " ;
strTotQuerey = strTotQuerey + "            WHEN '10' THEN '\ubc1c\uae09' " ;
strTotQuerey = strTotQuerey + "            WHEN '15' THEN '\uc7ac\ubc1c\uae09' " ;
strTotQuerey = strTotQuerey + "            WHEN '20' THEN '\uac31\uc2e0' " ;
strTotQuerey = strTotQuerey + "            WHEN '30' THEN '\ud3d0\uae30' " ;
strTotQuerey = strTotQuerey + "            WHEN '40' THEN '\ud6a8\ub825\uc815\uc9c0' " ;
strTotQuerey = strTotQuerey + "            WHEN '41' THEN '\ud6a8\ub825\ud68c\ubcf5' " ;
strTotQuerey = strTotQuerey + "            WHEN '45' THEN '\ud658\ubd88\ud3d0\uae30' " ;
strTotQuerey = strTotQuerey + "            ELSE '\ubc1c\uae09' " ;
strTotQuerey = strTotQuerey + "        END " ;
strTotQuerey = strTotQuerey + "        ) AS LASTSTATUSNM " ;
strTotQuerey = strTotQuerey + "    ,   A.LASTSTATUS " ;
strTotQuerey = strTotQuerey + "    ,   A.ISSUE_DATE " ;
strTotQuerey = strTotQuerey + "    ,   A.EXPIRE_DATE " ;
strTotQuerey = strTotQuerey + "    ,   A.EVENT_DATE    " ;
strTotQuerey = strTotQuerey + "    ,  (SELECT DN FROM LDAP_INFO WHERE SERIAL=A.SERIAL) AS DN  " ;
strTotQuerey = strTotQuerey + " FROM CERTS A " ;
strTotQuerey = strTotQuerey + " WHERE A.USERID IS NOT NULL " ;
strTotQuerey = strTotQuerey + baseCondQuery ;
strTotQuerey = strTotQuerey + "    ) C " ;
if ( strKeyword != "" ) {
	strTotQuerey = strTotQuerey + "    WHERE "+gb+" like '%"+ strKeyword +"%' " ;
}


String strQuery = "" ;
strQuery = strQuery + "SELECT C.SERIAL " ;
strQuery = strQuery + "    , C.USERID " ;
strQuery = strQuery + "    , C.USERNAME " ;
strQuery = strQuery + "    , C.USERIP " ;
strQuery = strQuery + "    , C.ISSUER_CODE " ;
strQuery = strQuery + "    , C.STATUS " ;
strQuery = strQuery + "    , C.STATUSNM " ;
strQuery = strQuery + "    , C.LASTSTATUSNM " ;
strQuery = strQuery + "    , C.LASTSTATUS " ;
strQuery = strQuery + "    , C.ISSUE_DATE " ;
strQuery = strQuery + "    , C.EXPIRE_DATE " ;
strQuery = strQuery + "    , C.EVENT_DATE " ;
strQuery = strQuery + "    , NVL(C.DN,'\ud3d0\uae30') AS DN " ;
strQuery = strQuery + "    , ROWNUM R " ;
strQuery = strQuery + "    , RANK() OVER (ORDER BY C.SERIAL DESC) AS RANKING " ;
strQuery = strQuery + " FROM ( " ;

strQuery = strQuery + "SELECT " ;
strQuery = strQuery + "        A.SERIAL " ;
strQuery = strQuery + "    ,   A.USERID " ;
strQuery = strQuery + "    ,   ( " ;
strQuery = strQuery + "			SELECT DISTINCT(nvl(USERNAME,'TEST\uc0ac\uc6a9\uc790'))  " ;
strQuery = strQuery + "			FROM USER_PWD  " ;
strQuery = strQuery + "			WHERE USERID=A.USERID " ;
strQuery = strQuery + "			) AS USERNAME " ;
strQuery = strQuery + "    ,   ( " ;
strQuery = strQuery + "			SELECT NVL(USERIP,'&nbsp;')  " ;
strQuery = strQuery + "			FROM USER_PWD  " ;
strQuery = strQuery + "			WHERE USERID=A.USERID " ;
strQuery = strQuery + "			) AS USERIP " ;
strQuery = strQuery + "    ,   A.ISSUER_CODE " ;
strQuery = strQuery + "    ,   A.STATUS " ;
strQuery = strQuery + "    ,  ( " ;
strQuery = strQuery + "          CASE A.STATUS " ;
strQuery = strQuery + "              WHEN 'I' THEN '\uc720\ud6a8' " ;
strQuery = strQuery + "              WHEN 'R' THEN '\ud398\uae30' " ;
strQuery = strQuery + "              WHEN 'S' THEN '\ud6a8\ub825\uc815\uc9c0' " ;
strQuery = strQuery + "              ELSE '\uc720\ud6a8' " ;
strQuery = strQuery + "          END " ;
strQuery = strQuery + "        ) AS STATUSNM " ;
strQuery = strQuery + "   ,  ( " ;
strQuery = strQuery + "        CASE A.LASTSTATUS " ;
strQuery = strQuery + "            WHEN '10' THEN '\ubc1c\uae09' " ;
strQuery = strQuery + "            WHEN '15' THEN '\uc7ac\ubc1c\uae09' " ;
strQuery = strQuery + "            WHEN '20' THEN '\uac31\uc2e0' " ;
strQuery = strQuery + "            WHEN '30' THEN '\ud3d0\uae30' " ;
strQuery = strQuery + "            WHEN '40' THEN '\ud6a8\ub825\uc815\uc9c0' " ;
strQuery = strQuery + "            WHEN '41' THEN '\ud6a8\ub825\ud68c\ubcf5' " ;
strQuery = strQuery + "            WHEN '45' THEN '\ud658\ubd88\ud3d0\uae30' " ;
strQuery = strQuery + "            ELSE '\ubc1c\uae09' " ;
strQuery = strQuery + "        END " ;
strQuery = strQuery + "        ) AS LASTSTATUSNM " ;
strQuery = strQuery + "    ,   A.LASTSTATUS " ;
strQuery = strQuery + "    ,   A.ISSUE_DATE " ;
strQuery = strQuery + "    ,   A.EXPIRE_DATE " ;
strQuery = strQuery + "    ,   A.EVENT_DATE    " ;
strQuery = strQuery + "    ,  (SELECT DN FROM LDAP_INFO WHERE SERIAL=A.SERIAL) AS DN  " ;
strQuery = strQuery + " FROM CERTS A " ;
strQuery = strQuery + " WHERE A.USERID IS NOT NULL " ;
strQuery = strQuery + baseCondQuery ;
strQuery = strQuery + "    ) C " ;
if ( strKeyword != "" ) {
	strQuery = strQuery + "    WHERE "+gb+" like '%"+ strKeyword +"%' " ;
}
strQuery = strQuery + " ORDER BY C.SERIAL DESC " ; 


try {
	connu = dsu.getConnection();
	//Creat Query and get results
	stmtu = connu.createStatement();

	rsu = stmtu.executeQuery(strTotQuerey);
	rsu.next();
    totalRecord = rsu.getInt(1); //\ucd1d \uce74\uc6b4\ud2b8\uc218

    out.write(_jsp_string1, 0, _jsp_string1.length);
    

response.setHeader("Content-Type", "application/vnd.ms-excel;charset=euc-kr");
response.setHeader("Content-Description", "stype=mso-number-format:'\\@'");  
response.setHeader("Content-Disposition", "attachment; filename=CertificateList_"+CurYYYMMDDHHMMSS+".xls");  
response.setHeader("Content-Description", "Certificates List");  


    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((fileName));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((CurTime));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((totalRecord));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    
Locale locale = java.util.Locale.KOREA;
SimpleDateFormat sdfr = new SimpleDateFormat("yyyy-MM-dd", locale);
java.util.Date today  = new java.util.Date(); 
String convertedToday = sdfr.format(today);

rsu = stmtu.executeQuery(strQuery);

int irs = 1 ;
while( rsu.next() ) {		


    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((irs));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rsu.getString("USERNAME")));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((rsu.getString("USERID")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rsu.getString("USERIP")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((rsu.getString("SERIAL")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rsu.getString("ISSUE_DATE")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rsu.getString("ISSUE_DATE")));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((rsu.getString("EXPIRE_DATE")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rsu.getString("DN")));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    if (rsu.getString("STATUS").equals("I")) {
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((getDateDiff(convertedToday, rsu.getString("EXPIRE_DATE"))));
    out.write('/');
    out.print((getDateDiff(rsu.getString("ISSUE_DATE"), rsu.getString("EXPIRE_DATE"))));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    }else{
    out.write(_jsp_string12, 0, _jsp_string12.length);
    }
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((rsu.getString("STATUSNM")));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((rsu.getString("LASTSTATUSNM")));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    
	irs++;
}

    out.write(_jsp_string17, 0, _jsp_string17.length);
    
} catch(Exception e) {
	e.printStackTrace();
} finally {
	rsu.close();
	connu.close();
}

    out.write(_jsp_string18, 0, _jsp_string18.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("certcenter64/inica70/excelDown.jsp"), -6813696153573188321L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string8;
  private final static char []_jsp_string15;
  private final static char []_jsp_string11;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  private final static char []_jsp_string16;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string17;
  private final static char []_jsp_string14;
  private final static char []_jsp_string1;
  private final static char []_jsp_string18;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  static {
    _jsp_string3 = " (".toCharArray();
    _jsp_string4 = " \uae30\uc900)</td>\r\n		</tr>\r\n	</table>\r\n	<table cellSpacing=\"0\" cellPadding=\"0\" style=\"width:2000px;\" border=\"0\">\r\n		<tr>\r\n			<td colspan=\"11\" class=\"default\" style=\"text-align:right;\">\r\n				\ucd1d <span style=\"font-weight:bold;color:#ff0033;\">".toCharArray();
    _jsp_string5 = "</span>\uac74\uc758 \uc778\uc99d\uc11c \ubc1c\uae09\ub0b4\uc5ed\uc774 \uc874\uc7ac\ud569\ub2c8\ub2e4.\r\n			</td>\r\n		</tr>\r\n	</table>\r\n	<table cellSpacing=\"0\" cellPadding=\"0\" style=\"width:2000px;\" border=\"0\" class=\"wTable\">\r\n		<tr>\r\n			<td class=\"wTableTdHeader\" style=\"background-color:#d9d9d9\" colspan=\"4\">\uc0ac\uc6a9\uc790 \uc815\ubcf4</td>\r\n			<td class=\"wTableTdHeader\" style=\"background-color:#d9d9d9\" colspan=\"7\">\uc778\uc99d\uc11c \uc815\ubcf4</td>\r\n		</tr>\r\n		<tr>\r\n			<td class=\"wTableTdHeader\" style=\"width:45px;\">\uc21c\ubc88</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:55px;\">\uc131\uba85</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:50px;\">\uc0ac\ubc88</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:80px;\">\uc811\uc18dIP</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:80px;\">\uc778\uc99d\uc11c<br>\uc2dc\ub9ac\uc5bc</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:120px;\">\uc778\uc99d\uc11c\ubc1c\uae09\uc77c</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:400px;\">\uc778\uc99d\uc11c \uc720\ud6a8\uae30\uac04 \uc2dc\uc791\uc77c ~ \uc885\ub8cc\uc77c</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:1025px;\">\uc778\uc99d\uc11c Subject DN\uac12</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:65px;\">\uc0ac\uc6a9\uac00\ub2a5<br />\ub0a8\uc740\uc77c\uc218</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:40px;\">\uc778\uc99d\uc11c<br>\uc0c1\ud0dc</td>\r\n			<td class=\"wTableTdHeader\" style=\"width:40px;\">\uc778\uc99d\uc11c<br>\ubcc0\uacbd<br>\ub0b4\uc6a9</td>\r\n		</tr>\r\n".toCharArray();
    _jsp_string8 = "</td>\r\n			<td class=\"wTableTdCell\" style=\"mso-number-format:'\\@';\">".toCharArray();
    _jsp_string15 = "</td>\r\n			<td class=\"wTableTdCell\" style=\"text-align:center;\">".toCharArray();
    _jsp_string11 = "</td>\r\n			<td class=\"wTableTdCell\" style=\"text-align:center;\">\r\n				".toCharArray();
    _jsp_string9 = "</td>\r\n			<td class=\"wTableTdCell\" style=\"text-align:center;mso-number-format:'\\@';\">".toCharArray();
    _jsp_string7 = "</td>\r\n			<td class=\"wTableTdCell\">".toCharArray();
    _jsp_string2 = "\r\n<style type=\"text/css\">\r\n.default {\r\n	font-size: 8pt;\r\n	font-family:\"\ub9d1\uc740 \uace0\ub515\", Dotum, Gulim, Verdana, AppleGothic, sans-serif;\r\n\r\n}\r\n\r\n.wTable {\r\n	border-top : solid 1px #c5c5c5;\r\n	border-left : solid 1px #c5c5c5;\r\n}\r\n.wTableTdHeader {\r\n	font-size: 8pt;\r\n	font-family:\"\ub9d1\uc740 \uace0\ub515\", Dotum, Gulim, Verdana, AppleGothic, sans-serif;\r\n	border-right : solid 1px #c5c5c5;\r\n	border-bottom : solid 1px #c5c5c5;\r\n	text-align : center;\r\n	font-weight : bold;\r\n	background-color : #eeeeee ;\r\n	padding : 4px;\r\n}\r\n.wTableTdCell {\r\n	font-size: 8pt;\r\n	font-family:\"\ub9d1\uc740 \uace0\ub515\", Dotum, Gulim, Verdana, AppleGothic, sans-serif;\r\n	border-right : solid 1px #c5c5c5;\r\n	border-bottom : solid 1px #c5c5c5;\r\n	font-weight : normal;\r\n	background-color : #ffffff ;\r\n	padding : 4px;\r\n}\r\n</style>\r\n\r\n</head> \r\n<body>\r\n	<table cellSpacing=\"0\" cellPadding=\"0\" style=\"width:2000px;\" border=\"0\">\r\n		<tr>\r\n			<td colspan=\"11\" class=\"default\">".toCharArray();
    _jsp_string12 = "\r\n				".toCharArray();
    _jsp_string16 = "</td>\r\n		</tr>\r\n\r\n		\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string10 = " ~ ".toCharArray();
    _jsp_string17 = "\r\n						\r\n	</table>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string14 = "\r\n			</td>\r\n			<td class=\"wTableTdCell\" style=\"text-align:center;\">".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\" />\r\n<title>\uc778\uc99d\uc11c \ubc1c\uae09 \ub0b4\uc5ed</title>\r\n\r\n\r\n ".toCharArray();
    _jsp_string18 = "\r\n".toCharArray();
    _jsp_string6 = "\r\n		<tr>\r\n			<td class=\"wTableTdCell\">".toCharArray();
    _jsp_string13 = "\uc77c\r\n				".toCharArray();
  }
}
