/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.Date.*;
import java.text.SimpleDateFormat;

public class _test2__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  public String toPad(String str, int strLen){
  		String toVal = null;
  		int intGap = 0 ;
  		String strPad = "x";
  
  
  
  		//\ub118\uc5b4\uc628 \ubb38\uc790\uc5f4(str)\uc774 \ucc44\uc6cc\uc918\uc57c\ud560 \ud14d\uc2a4\ud2b8\uae38\uc774(strLen)\ubcf4\ub2e4 \uc791\ub2e4\uba74
  		if (str.length() < strLen) {
  			intGap = strLen - str.length() ;
  			for (int i=1; i <= intGap; i++){
  				strPad += strPad ; 
  			}
  		}
  
  		//toVal = str + strPad ;
  		toVal = strPad ;
  		//toVal = Integer.toString(intGap);
  		return toVal;
  }
  
  public String en(String ko){
  	        /**/
  	        String new_str = null;
  	        try{        
  	                new_str  = new String(ko.getBytes("KSC5601"), "8859_1");
  	        } catch(UnsupportedEncodingException ex) {ex.printStackTrace(); }
  	        return new_str;
  	        /**/
  	        //return ko;
  }
  
  
  public static String Padding(String str, int len, char padding) {
  
  	//\ub0b4\uc6a9\uc774 \uc5c6\ub294 \uacbd\uc6b0.
  	if (str == null)
  	return "";
  
  	//\uc0ac\uc774\uc988\uac00 0\ubcf4\ub2e4 \uc791\uc740\uacbd\uc6b0.
  	if (len <= 0)
  	return str;
  
  	byte[] strbyte = null;
  
  	strbyte = str.getBytes();//getBytes("EUC-KR")
  	int strbyteLen = strbyte.length;
  
  	int strbyteLenTmp = 0;
  	StringBuffer strTmp = new StringBuffer();
  
  	if (strbyteLen < len) {//\ubb38\uc790\uc5f4 \ubcf4\ub2e4  \uc790\ub97c \uae38\uc774\uac00 \ub354 \ud070 \uacbd\uc6b0.
  
  		strbyteLenTmp = len - strbyteLen;
  
  		for (int i = 0; i < strbyteLenTmp; i++) {//\ud328\ub529 \ubb38\uc790\ub85c \ucc44\uc6b4\ub2e4.
  			strTmp.append(padding);
  		}
  
  		//\ubb38\uc790 \ud569\uce5c\ud6c4 \ubb38\uc790\uc5f4 \uae38\uc774 \ub2e4\uc2dc \uad6c\ud55c\ub2e4.
  		str = str + strTmp.toString();
  		strbyte = str.getBytes();
  		strbyteLen = strbyte.length;
  	}
  
  	if (strbyteLen == len) {
  		return str;
  	}
  
  	char[] charArray = str.toCharArray();
  
  	int checkLimit = len;
  	for (int i = 0; i < charArray.length; i++) {
  		if (charArray[i] < 256) {
  			checkLimit -= 1;
  		} else {
  			checkLimit -= 2;
  		}
  
  		if (checkLimit <= 0) {
  		break;
  		}
  	}
  
  	//\ub300\uc0c1 \ubb38\uc790\uc5f4 \ub9c8\uc9c0\ub9c9 \uc790\ub9ac\uac00 2\ubc14\uc774\ud2b8\uc758 \uc911\uac04\uc77c \uacbd\uc6b0 \uc81c\uac70\ud568
  	byte[] newByte = new byte[len + checkLimit];
  
  	for (int i = 0; i < newByte.length; i++) {
  		newByte[i] = strbyte[i];
  	}
  
  	return new String(newByte);
  
  }
  

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String keyval = en("KEPCO-SSO \ubc1c\uae09\uc6a9\ud638\ub294 [000000]\uc785\ub2c8\ub2e4.");

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((keyval));
    out.write('(');
    out.print((keyval.length()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((Padding(keyval, 81, (char)0x00)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((Padding(keyval, 81,(char)0x00).length()));
    out.write(_jsp_string4, 0, _jsp_string4.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("test2.jsp"), -1943830003230419552L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n\uc804\ub2ec\ubb38\uc790 : ".toCharArray();
    _jsp_string4 = "<br><br><br><br>".toCharArray();
    _jsp_string3 = "<br>\r\n\ubb38\uc790\uae38\uc774 : ".toCharArray();
    _jsp_string2 = ")<br>\r\n\uc804\uc1a1\ubb38\uc790 : ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
