/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp._certcenter64._inica70;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public class _ini_0certinfo_0view__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
Context ic = new InitialContext();
DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/INIRA");
ResultSet rs = null;

Connection conn = null;
Statement stmt = null;

int i = 0;

try {

	conn = ds.getConnection();
	//Creat Query and get results
	stmt = conn.createStatement();

	String sql = "SELECT ltrim(serial,'0') as serial, policy, timeid, subject_dn, cid, racode, status, to_char(issue_date,'yyyymmdd'), to_char(expire_date,'yyyymmdd') FROM CERT_INFO order by issue_date, to_number(serial) desc";

	rs = stmt.executeQuery(sql);

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
	while (rs.next()){

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((rs.getString(1)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(2)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(3)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(4)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(6)));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((rs.getString(8)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(9)));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    
	}

    out.write(_jsp_string6, 0, _jsp_string6.length);
    
}
catch (Exception e){
	e.printStackTrace();

    out.write(_jsp_string7, 0, _jsp_string7.length);
    
}finally {
		rs.close();
		
		conn.close();
	}

    out.write(_jsp_string8, 0, _jsp_string8.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("certcenter64/inica70/ini_certinfo_view.jsp"), -2081948358136886623L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string6;
  static {
    _jsp_string2 = "\n<tr>\n	<td>".toCharArray();
    _jsp_string7 = "\n<h4>\uc5d0\ub7ec\uac00 \ubc1c\uc0dd\ud558\uc600\uc2b5\ub2c8\ub2e4.</h4>\n".toCharArray();
    _jsp_string8 = "\n</BODY>\n</HTML>\n".toCharArray();
    _jsp_string0 = "\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<HTML>\n<HEAD>\n<TITLE>\uae08\uc77c \ubc1c\uae09 \ub0b4\uc5ed</TITLE>\n<meta http-equiv=\"content-type\" content=\"text/html; charset=euc-kr\">\n</HEAD>\n<BODY>\n".toCharArray();
    _jsp_string4 = "</td>\n	<td>\uc720\ud6a8</td>\n	<td>".toCharArray();
    _jsp_string3 = "</td>\n	<td>".toCharArray();
    _jsp_string5 = "</td>\n</tr>\n".toCharArray();
    _jsp_string1 = "\n<h3 align=\"center\">\uae08\uc77c \uc778\uc99d\uc11c \ubc1c\uae09 \ub0b4\uc5ed</h3>\n<table border = \"1\" align=\"center\">\n\n<tr bgcolor = \"C2C0C1\"> \n	<td>\uc2dc\ub9ac\uc5bc\ubc88\ud638</td>\n	<td>\uc778\uc99d\uc815\ucc45\ucf54\ub4dc</td>\n	<td>\uac00\uc785\uc790ID</td>\n	<td>\uac00\uc785\uc790DN</td>\n	<td>\ub4f1\ub85d\ub300\ud589\uae30\uad00\ucf54\ub4dc</td>\n	<td>\uc778\uc99d\uc11c\uc0c1\ud0dc</td>\n	<td>\ubc1c\uae09\uc77c\uc790</td>\n	<td>\ub9cc\ub8cc\uc77c\uc790</td>\n</tr>\n".toCharArray();
    _jsp_string6 = "\n\n</table>\n".toCharArray();
  }
}
