/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public class _insatest__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
Context ic = new InitialContext();
DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/INSA");
ResultSet rs = null;

Connection conn = null;
Statement stmt = null;

try{
	conn = ds.getConnection();
	//Creat Query and get results
	stmt = conn.createStatement();
	rs = stmt.executeQuery("SELECT EMPNO, DEPTNO, MAILNO, NAME, PASSWD, LEVELNM FROM IRIS.V_INSA");
		

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
	while (rs.next()){

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((rs.getString("EMPNO")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString("DEPTNO")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString("MAILNO")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString("NAME")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString("PASSWD")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString("LEVELNM")));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
	}
	rs.close();

    out.write(_jsp_string5, 0, _jsp_string5.length);
    
			

	}
	catch(Exception ex){
		ex.printStackTrace();
} finally {
	stmt.close();
	conn.close();
}

    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("insatest.jsp"), -1334428271197713662L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  static {
    _jsp_string2 = "\n<tr>\n	<td>".toCharArray();
    _jsp_string6 = "\n</body>\n</html>\n\n\n".toCharArray();
    _jsp_string3 = "</td>\n	<td>".toCharArray();
    _jsp_string1 = "\n<html>\n<head>\n<title>certificate</title>\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\n	<script language=\"javascript\">\n	function new_window(url)\n	{\n		//new_win= window.open(url,'new_win','status=yes,scrollbars=no,resizble=no,width=500,height=550');\n		window.location = url;\n	}\n	</script>\n<style type=\"text/css\">\n<!--\n.text {  font-family: \"\ub3cb\uc6c0\"; font-size: 11px; text-decoration: none; line-height: 15px}\n-->\n</style>\n</head>\n\n<body bgcolor=\"#FFFFFF\" text=\"#000000\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n<center>\n<h3 align=\"center\">\uc778\uc0ac\uc815\ubcf4\ud14c\uc2a4\ud2b8</h3>\n<table border = \"1\" align=\"center\">\n\n<tr bgcolor = \"C2C0C1\"> \n	<td>\uc0ac\ubc88</td>\n	<td>\ubd80\uc11c\ucf54\ub4dc</td>\n	<td>\uba54\uc77c\uc8fc\uc18c</td>\n	<td>\uc774\ub984</td>\n	<td>PWD</td>\n	<td>\uc9c1\uae09</td>\n</tr>\n".toCharArray();
    _jsp_string4 = "</td>\n</tr>\n".toCharArray();
    _jsp_string0 = "\n\n".toCharArray();
    _jsp_string5 = "\n\n</table>\n".toCharArray();
  }
}
