/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.util.Date.*;
import java.text.SimpleDateFormat;
import java.lang.*;
import java.lang.String.*;
import java.text.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import kepco.*;

public class _websmssend2__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  //SendMSG\ub9cc\ub4e4\uae30
  public String en(String ko){
  	String new_str = null;
  	try{        
  		new_str  = new String(ko.getBytes("KSC5601"), "8859_1");
  	} catch(UnsupportedEncodingException ex) {ex.printStackTrace(); }
  		return new_str;
  }
  
  public String ko(String en){
  	String new_str = null;
  	try{              
  		try{
  			new_str  = new String(en.getBytes("8859_1"), "KSC5601");                
  		}
  		catch(UnsupportedEncodingException ex) {
  				ex.printStackTrace(); 
  		}
  	}catch(NullPointerException e) {	
  		System.out.println("Null  " + en);
  		new_str = en;
  	}
  	return new_str;
  }
  
  public String fillSpace(String text, int size){
  	String tmpStr = "";
  	try{ 
  		tmpStr = new String(text.getBytes("KSC5601"),"8859_1"); 
  	}catch(UnsupportedEncodingException e){
  		e.printStackTrace(); 
  	} 
  	int diff = size - tmpStr.length();
  	if (diff > 0 ){
  		for (int i = 0 ; i < diff ; i++) {
  			text += " ";
  			//text +=  (char)0;
  		}
  		StringBuffer sb1 = new StringBuffer(text);
  		sb1.setLength(size);
  		text = sb1.toString();
  	}
  	else{
  		StringBuffer sb = new StringBuffer(text);
  		sb.setLength(size);
  		text = sb.toString();
  	}
  
  	return text;
  }
  
  public String getMessage(String str, int addCnt) {
  	String strAdd ="";	
  	for(int i=0; i <addCnt ; i++){
  		strAdd += " ";
  	}		
  	return str+strAdd;
  }
  
  public String rtnMessage(String MsgCode){
  	String MsgStr = "" ;
  	if (MsgCode.equals("2000")) {
  			MsgStr = "\uc778\uc99d\uc13c\ud130 \ubc1c\uc1a1 \ubaa8\ub4c8 \uc624\ub958";
  	}else if (MsgCode.equals("9999")) {
  			MsgStr = "\uc131\uacf5";
  	}else if (MsgCode.equals("1000")) {
  			MsgStr = "SMS \ud504\ub85c\uc138\uc2a4 \uc624\ub958(SMS \ub370\ubaac \ud504\ub85c\uc138\uc2a4 \uc815\uc9c0)";
  	}else if (MsgCode.equals("1001")) {
  			MsgStr = "\uc804\uc1a1 \ub370\uc774\ud130\ud615\uc2dd \uc624\ub958";
  	}else if (MsgCode.equals("1002")) {
  			MsgStr = "\uc11c\ubc84\uac04 \uc804\uc1a1\uc2dc\uac04 \ucd08\uacfc \uc624\ub958";
  	}else if (MsgCode.equals("1100")) {
  			MsgStr = "\ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc811\uc18d \uc624\ub958 \ub610\ub294 \ub3d9\uc2dc \uc811\uc18d \uacfc\ub2e4";
  	}else if (MsgCode.equals("1101")) {
  			MsgStr = "\ub370\uc774\ud130\ubca0\uc774\uc2a4 Query \uc624\ub958";
  	}else if (MsgCode.equals("1200")) {
  			MsgStr = "\uc0ac\uc5c5\uc18c \uc11c\ube44\uc2a4 \uc624\ub958 (\uc798\ubabb\ub41c \uc0ac\uc5c5\uc18c \ucf54\ub4dc \uc804\uc1a1)";
  	}else if (MsgCode.equals("2000")) {
  			MsgStr = "\uc778\uc99d\uc13c\ud130 \ubc1c\uc1a1 \ubaa8\ub4c8 \uc624\ub958";
  	}else {
  			MsgStr = "\uc131\uacf5";
  	
  	}
  	return MsgStr ;
  }
  
  //1. 9999 : \uc131\uacf5(\uba54\uc138\uc9c0 \uc815\uc0c1 \ucc98\ub9ac)
  //2. 1000 : SMS \ud504\ub85c\uc138\uc2a4 \uc624\ub958(SMS \ub370\ubaac \ud504\ub85c\uc138\uc2a4\uac00 \uc815\uc9c0\ub410\uc744 \uacbd\uc6b0)
  //3. 1001 : \uc804\uc1a1 \ub370\uc774\ud130\ud615\uc2dd \uc624\ub958(\uc804\uc1a1 \ub370\uc774\ud130\ud615\uc2dd\uc774 \uaddc\uc815\uc5d0 \ub9de\uc9c0 \uc54a\uc744 \uacbd\uc6b0)
  //4. 1002 : \uc11c\ubc84\uac04 \uc804\uc1a1\uc2dc\uac04 \ucd08\uacfc \uc624\ub958(\uc11c\ubc84\uac04 \uc5f0\uacb0 \ud6c4 \uc77c\uc815\uc2dc\uac04\ub3d9\uc548 \ub370\uc774\ud130 \uc1a1\uc218\uc2e0\uc774 \uc774\ub8e8\uc5b4\uc9c0\uc9c0 \uc54a\uc744 \uacbd\uc6b0)
  //5. 1100 : \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc811\uc18d \uc624\ub958(\ub370\uc774\ud130\ubca0\uc774\uc2a4\uac00 \uc815\uc9c0\ub418\uc5c8\uac00\ub098 \ub3d9\uc2dc \uc811\uc18d\uc774 \ub9ce\uc744 \uacbd\uc6b0)
  //6. 1101 : \ub370\uc774\ud130\ubca0\uc774\uc2a4 Query \uc624\ub958(\ub370\uc774\ud130\ubca0\uc774\uc2a4 Query \ubc0f \ub370\uc774\ud130 \ud615\uc2dd\uc5d0 \ub9de\uac8c \uc218\uc2e0\ud55c \ud6c4 \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uac80\uc0c9\uc2dc \uc798\ubabb\ub41c \uacbd\uc6b0);
  //7. 1200 : \uc0ac\uc5c5\uc18c \uc11c\ube44\uc2a4 \uc624\ub958 (\uc0ac\uc5c5\uc18c \ucf54\ub4dc\uac00 \uc798\ubabb\ub41c \uacbd\uc6b0)
  //8. 2000 : \ubcf4\ub0b4\ub294\ucabd \uc18c\ucf13\ud1b5\uc2e0 \uc624\ub958
  ////////////////////////////////////////////////////

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String strIsInsa = request.getParameter("strIsInsa"); //SMS\uc778\uc0ac\uc815\ubcf4 \uc5f0\ub3d9 \uc720\ubb34
if (strIsInsa.equals("") || strIsInsa == null) {
	strIsInsa = "N"; //default\ub294 \uc5f0\ub3d9\ud558\uc9c0 \uc54a\uc74c
}

String empno = request.getParameter("empno"); //\uc0ac\ubc88
String tmid = request.getParameter("tmid");//\ud0c0\uc784\uc544\uc774\ub514
String seq = "" ;
String strSql = "" ;
String org_phone = request.getParameter("org_phone"); //DB\uc5d0 \uc800\uc7a5\ub41c \ubc88\ud638
String userName = request.getParameter("userName"); // \uc0ac\uc6a9\uc790\uba85

String phone1 = request.getParameter("phone1"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6381
String phone2 = request.getParameter("phone2"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6382
String phone3 = request.getParameter("phone3"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6383
String phone = phone1 + "-" + phone2 + "-" + phone3 ; //\uc5f0\ub77d\ucc98 \uc870\ud569

String orgPhone = org_phone.replace("-","");
String sendPhone = phone1 + phone2 + phone3 ; //\uc5f0\ub77d\ucc98 \uc870\ud569

String sendCnt = "00001"; //\ubcf4\ub0b4\uc57c\ud560 SMS\uc804\uc1a1 \uc218

//validation check
if (empno.equals("") || empno==null || phone1.equals("") || phone1==null || phone2.equals("") || phone2==null || phone3.equals("") || phone3==null || tmid.equals("") || tmid==null ){
	response.setCharacterEncoding("EUC-KR");
	PrintWriter writer = response.getWriter();
	writer.println("<script type='text/javascript'>");
	writer.println("alert('SMS\uc778\uc99d\uc744 \uc704\ud55c \uc0ac\ubc88 \ubc0f \uc804\ud654\ubc88\ud638\uac00 \ub204\ub77d\ub418\uc5b4 \uc804\ub2ec\ub418\uc5c8\uc2b5\ub2c8\ub2e4.');");
	writer.println("location.href='websmsform.jsp';");
	writer.println("</script>");
	writer.flush();
	return;
} // end of check all of validation 


//SMS seq make
seq = tmid + "_" + empno + "_" + request.getRemoteAddr() ; // 20140709172427_ex099129_255.255.255.255


int cnt_user = 0 ; // \uc0ac\ubc88\uc5d0 \ud574\ub2f9\ud558\ub294 \uc0ac\uc6a9\uc790 \uc874\uc7ac \uc720\ubb34(0:\uc5c6\uc74c, \uadf8\uc678 \uc874\uc7ac)

int phoneLen = 0 ;

if (orgPhone.equals(sendPhone)){//\uc778\uc0ac\ud14c\uc774\ube14\uc5d0 \uc800\uc7a5\ub41c \uc804\ud654\ubc88\ud638\uc640 \uc785\ub825\ud55c \uc804\ud654\ubc88\ud638\uac00 \uac19\uc744\ub54c\ub294 \ud55c\ubc88\ub9cc \ubcf4\ub0c4
	sendCnt = "00001";
}else{
	if (org_phone.equals("010-0000-0000")) { //\uc778\uc0ac\uc815\ubcf4\uc5d0 \uc5f0\ub77d\ucc98 \ub4f1\ub85d\uc774 \uc548\ub428..\uc774\uac70 \uc5b4\ucf00\ucc98\ub9ac\ud560\uc9c0
		sendCnt = "00001";
	}else{
		sendCnt = "00002";//\uc778\uc0ac\ud14c\uc774\ube14\uc5d0 \uc800\uc7a5\ub41c \uc804\ud654\ubc88\ud638\uc640 \uc785\ub825\ud55c \uc804\ud654\ubc88\ud638\uac00 \ub2e4\ub974\uba74 \ub450\ubc88 \ubc1c\uc1a1
	}
}

//////////////////////////////////////////////////////////////////////////////////////////
//SMS\uc778\uc99d\ubc88\ud638 \ub9cc\ub4e4\uae30 START   /////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
String certkey = "000000";

int RandNum = (int)(Math.random()*1000000 + 1);
DecimalFormat dt = new DecimalFormat("000000");
certkey = dt.format(RandNum);
String strMsgText ="[\ud55c\uad6d\uc804\ub825\uacf5\uc0ac] \uc778\ud130\ub137\ub9dd \uc778\uc99d\uc11c \ubc1c\uae09\uc6a9\n\uc778\uc99d\ubc88\ud638\ub294 ["+certkey+"]\uc785\ub2c8\ub2e4.";
//////////////////////////////////////////////////////////////////////////////////////////
//SMS\uc778\uc99d\ubc88\ud638 \ub9cc\ub4e4\uae30 END   ///////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////
//1. 9999 : \uc131\uacf5(\uba54\uc138\uc9c0 \uc815\uc0c1 \ucc98\ub9ac)
//2. 1000 : SMS \ud504\ub85c\uc138\uc2a4 \uc624\ub958(SMS \ub370\ubaac \ud504\ub85c\uc138\uc2a4\uac00 \uc815\uc9c0\ub410\uc744 \uacbd\uc6b0)
//3. 1001 : \uc804\uc1a1 \ub370\uc774\ud130\ud615\uc2dd \uc624\ub958(\uc804\uc1a1 \ub370\uc774\ud130\ud615\uc2dd\uc774 \uaddc\uc815\uc5d0 \ub9de\uc9c0 \uc54a\uc744 \uacbd\uc6b0)
//4. 1002 : \uc11c\ubc84\uac04 \uc804\uc1a1\uc2dc\uac04 \ucd08\uacfc \uc624\ub958(\uc11c\ubc84\uac04 \uc5f0\uacb0 \ud6c4 \uc77c\uc815\uc2dc\uac04\ub3d9\uc548 \ub370\uc774\ud130 \uc1a1\uc218\uc2e0\uc774 \uc774\ub8e8\uc5b4\uc9c0\uc9c0 \uc54a\uc744 \uacbd\uc6b0)
//5. 1100 : \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc811\uc18d \uc624\ub958(\ub370\uc774\ud130\ubca0\uc774\uc2a4\uac00 \uc815\uc9c0\ub418\uc5c8\uac00\ub098 \ub3d9\uc2dc \uc811\uc18d\uc774 \ub9ce\uc744 \uacbd\uc6b0)
//6. 1101 : \ub370\uc774\ud130\ubca0\uc774\uc2a4 Query \uc624\ub958(\ub370\uc774\ud130\ubca0\uc774\uc2a4 Query \ubc0f \ub370\uc774\ud130 \ud615\uc2dd\uc5d0 \ub9de\uac8c \uc218\uc2e0\ud55c \ud6c4 \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uac80\uc0c9\uc2dc \uc798\ubabb\ub41c \uacbd\uc6b0);
//7. 1200 : \uc0ac\uc5c5\uc18c \uc11c\ube44\uc2a4 \uc624\ub958 (\uc0ac\uc5c5\uc18c \ucf54\ub4dc\uac00 \uc798\ubabb\ub41c \uacbd\uc6b0)
//8. 2000 : \ubcf4\ub0b4\ub294\ucabd \uc18c\ucf13\ud1b5\uc2e0 \uc624\ub958

String SENDIP = "203.248.44.150";
int SENDPORT = 7904;


int iCLASSCODE = 5 ;
int iPASSWORD = 4 ;
int iKEY = 15 ;
int iRECVPHONE = 15 ;
int iCALLBACK = 15 ;
int iMESSAGE = 80 ;
int iEMPNO = 8 ;
int iREFCNT = 5 ;

String CLASSCODE = "IDMKL" ; // 5 + 1
String PASSWORD = "DIST"; // 4 + 1


String KEY = "000000000000001";//15 + 1
Locale locale = java.util.Locale.KOREA;
SimpleDateFormat sdfr = new SimpleDateFormat("yyyyMMddHHmmss", locale);
String convertedTime = sdfr.format(new java.util.Date());
KEY = convertedTime ;

String RECVPHONE = sendPhone ;//("01099117557" 15 + 1) 
String REFPHONE = org_phone;

String CALLBACK = "0234561166"; //15 + 1
String MESSAGE = strMsgText ; //80 + 1
String EMPNO = empno ; // 8 + 1
String REFCNT = "00001"; // 5 + 1



String SEND_MSG = null ;



SEND_MSG = fillSpace(CLASSCODE, iCLASSCODE) + (char)0 ;	
SEND_MSG = SEND_MSG + fillSpace(PASSWORD, iPASSWORD) + (char)0 ;	
SEND_MSG = SEND_MSG + fillSpace(KEY, iKEY) + (char)0 ;	
SEND_MSG = SEND_MSG + fillSpace(RECVPHONE, iRECVPHONE) + (char)0 ;	
SEND_MSG = SEND_MSG + fillSpace(CALLBACK, iCALLBACK) + (char)0  ;	

int fCnt = 0 ;
if (fillSpace(MESSAGE,iMESSAGE).getBytes().length > iMESSAGE ){
	if(MESSAGE.getBytes().length < iMESSAGE ){
		fCnt = iMESSAGE-MESSAGE.getBytes().length;
		MESSAGE = getMessage(MESSAGE,fCnt);
	}
	SEND_MSG = SEND_MSG + MESSAGE  + (char)0 ;	
}else{
	SEND_MSG = SEND_MSG + fillSpace(MESSAGE,iMESSAGE) + (char)0 ;	
}
//SEND_MSG = SEND_MSG + getMessage(MESSAGE,81) ;

SEND_MSG = SEND_MSG + fillSpace(EMPNO,iEMPNO)  + (char)0;	
SEND_MSG = SEND_MSG + fillSpace(REFCNT,iREFCNT )  + (char)0;	



////////////////////////////////////////////////////
//  \uc218\uc2e0 \ucf54\ub4dc ///////////////////////////////////
String RETURNCODE = "2000";
String RETURNMSG = "" ;



String strRef = "2000";
String RefMsg = "KEPCO-SSO \uc778\uc99d\uc11c\ubc1c\uae09\uc6a9 \uc778\uc99d\ubc88\ud638\uc694\uccad\uc54c\ub9bc : "+ phone1 + "-" + phone2 + "-" + phone3  ;
String RefKey = KEY + "1" ;

String RefSMSMsg = "";
if (sendCnt.equals("00002")) {
	//\uc804\ud654\ubc88\ud638\uac00 \ub2e4\ub97c\ub54c\ub294 \uc6d0 \uc0ac\uc6a9\uc790 \uc804\ud654\ubc88\ud638\ub85c \uba54\uc138\uc9c0 \ub9ac\ud134\ud558\uc790
	RefSMSMsg = fillSpace(CLASSCODE, iCLASSCODE) + (char)0 ;	
	RefSMSMsg = RefSMSMsg + fillSpace(PASSWORD, iPASSWORD) + (char)0 ;	
	RefSMSMsg = RefSMSMsg + fillSpace(RefKey, iKEY) + (char)0 ;	
	RefSMSMsg = RefSMSMsg + fillSpace(orgPhone, iRECVPHONE) + (char)0 ;	
	RefSMSMsg = RefSMSMsg + fillSpace(CALLBACK, iCALLBACK) + (char)0  ;	

	int fCnt1 = 0 ;
	if (fillSpace(RefMsg,iMESSAGE).getBytes().length > iMESSAGE ){
		if(RefMsg.getBytes().length < iMESSAGE ){
			fCnt1 = iMESSAGE-RefMsg.getBytes().length;
			RefMsg = getMessage(RefMsg,fCnt1);
		}
		RefSMSMsg = RefSMSMsg + RefMsg  + (char)0 ;	
	}else{
		RefSMSMsg = RefSMSMsg + fillSpace(RefMsg,iMESSAGE) + (char)0 ;	
	}
	//SEND_MSG = SEND_MSG + getMessage(MESSAGE,81) ;

	RefSMSMsg = RefSMSMsg + fillSpace(EMPNO,iEMPNO)  + (char)0;	
	RefSMSMsg = RefSMSMsg + fillSpace(REFCNT,iREFCNT )  + (char)0;	
}


//SMS\ubc1c\uc1a1\uc744 \uc704\ud55c \ud074\ub77c\uc774\uc5b8\ud2b8 \uac1d\uccb4 \uc0dd\uc131
SmsClient sms = new SmsClient();
RETURNCODE = sms.SendSMS(SENDIP, SENDPORT, SEND_MSG);

RETURNCODE = RETURNCODE.trim();
RETURNMSG = rtnMessage(RETURNCODE);


if (sendCnt.equals("00002")) {
	strRef = sms.SendSMS(SENDIP, SENDPORT, RefSMSMsg).trim();
}

//SMS\uc815\ubcf4 db insert
Context icu = new InitialContext();
DataSource dsu = (DataSource) icu.lookup("java:comp/env/jdbc/INICA");
//ResultSet rsu = null;

Connection connu = null;
//Statement stmtu = null;
PreparedStatement pstmtu = null;

strSql = "INSERT INTO SMS_LOG ( SEQ, USERID, USERIP, SMSNUM, RETCODE)  VALUES ( '"+ seq +"', '"+ empno +"', '"+ request.getRemoteAddr() +"', '"+ certkey +"', '"+ RETURNCODE +"' )" ;


try {
	connu = dsu.getConnection();
	//stmtu = connu.createStatement();
	pstmtu = connu.prepareStatement(strSql);
	pstmtu.executeUpdate();

} catch(Exception e) {
	e.printStackTrace();
} finally {
	pstmtu.close();
	connu.close();
}


    out.write(_jsp_string1, 0, _jsp_string1.length);
     
if (RETURNCODE.equals("99991001")) { //\uc815\uc0c1

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((RETURNMSG));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((certkey));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
}else if (RETURNCODE.equals("9999")) { //\uc804\uc1a1\ub370\uc774\ud130\ud615\uc2dd

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((RETURNMSG));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((certkey));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
}else if (RETURNCODE.equals("1001")) { //\uc804\uc1a1\ub370\uc774\ud130\ud615\uc2dd \uc624\ub958\uc9c0\ub9cc \uc7a0\uc2dc \uc2a4\ud0b5

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((RETURNMSG));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((certkey));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((certkey));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    
}else{

    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((RETURNMSG));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((certkey));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
}	

    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((RETURNCODE));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((orgPhone));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((sendPhone));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((REFCNT));
    out.write(_jsp_string13, 0, _jsp_string13.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("websmssend2.jsp"), 6594294448970025710L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string10;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string5;
  private final static char []_jsp_string13;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string12;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  static {
    _jsp_string10 = "<br />\r\norgPhone : ".toCharArray();
    _jsp_string1 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\" />\r\n<title>SMS \uc778\uc99d\ud558\uae30</title>\r\n<script  type=\"text/javascript\" language=\"javascript\">\r\nfunction  fncConfirm() {\r\n".toCharArray();
    _jsp_string8 = "\r\n	\r\n	alert(\"[".toCharArray();
    _jsp_string5 = "]SMS\uc785\ub825\ub780\uc5d0 ".toCharArray();
    _jsp_string13 = "<br /> -->\r\n</body>\r\n</html>".toCharArray();
    _jsp_string9 = "\r\n}\r\n</script>\r\n\r\n</head>\r\n<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" onload=\"fncConfirm();\">\r\n<!-- RETURNCODE : ".toCharArray();
    _jsp_string11 = "<br />\r\nsendPhone : ".toCharArray();
    _jsp_string3 = "]SMS\uc778\uc99d\ubc88\ud638\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\\n\\n\uc804\uc1a1\ubc1b\uc73c\uc2e0 \uc778\uc99d\ubc88\ud638\ub97c \uc785\ub825\ud558\uc2ed\uc2dc\uc624.\");\r\n	//opener.readForm.smschk.value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string4 = "\";\r\n	opener.readForm.sms.style.background=\"#ffffff\";\r\n	opener.readForm.sms.disabled=false;\r\n	opener.setTimerOn();\r\n	window.close();\r\n".toCharArray();
    _jsp_string7 = "\";\r\n	opener.readForm.sms.style.background=\"#ffffff\";\r\n	opener.readForm.sms.disabled=false;\r\n	opener.setTimerOn();\r\n	window.close();	\r\n".toCharArray();
    _jsp_string12 = "<br />\r\nREFCNT : ".toCharArray();
    _jsp_string2 = "\r\n	alert(\"[".toCharArray();
    _jsp_string6 = "\uc744(\ub97c) \uc785\ub825\ud558\uc2ed\uc2dc\uc624.\");\r\n	//opener.readForm.smschk.value=\"".toCharArray();
  }
}
