/*
 * JSP generated by Resin Professional 4.0.38 (built Tue, 17 Dec 2013 09:49:45 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.lang.*;
import java.lang.String.*;
import java.text.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public class _websmssend__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String strIsInsa = request.getParameter("strIsInsa"); //SMS\uc778\uc0ac\uc815\ubcf4 \uc5f0\ub3d9 \uc720\ubb34
if (strIsInsa.equals("") || strIsInsa == null) {
	strIsInsa = "N"; //default\ub294 \uc5f0\ub3d9\ud558\uc9c0 \uc54a\uc74c
}


String empno = request.getParameter("empno"); //\uc0ac\ubc88
String old_phone = request.getParameter("old_phone"); //DB\uc5d0 \uc800\uc7a5\ub41c \ubc88\ud638
String userName = request.getParameter("userName"); // \uc0ac\uc6a9\uc790\uba85

String phone1 = request.getParameter("phone1"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6381
String phone2 = request.getParameter("phone1"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6382
String phone3 = request.getParameter("phone1"); //\uc9c1\uc811 \uc785\ub825\ud55c \ubc88\ud6383
String phone = phone1 + "-" + phone2 + "-" + phone3 ; //\uc5f0\ub77d\ucc98 \uc870\ud569


//validation check
if (empno.equals("") || empno==null || phone1.equals("") || phone1==null || phone2.equals("") || phone2==null || phone3.equals("") || phone3==null ){
	response.setCharacterEncoding("EUC-KR");
	PrintWriter writer = response.getWriter();
	writer.println("<script type='text/javascript'>");
	writer.println("alert('SMS\uc778\uc99d\uc744 \uc704\ud55c \uc0ac\ubc88 \ubc0f \uc804\ud654\ubc88\ud638\uac00 \ub204\ub77d\ub418\uc5b4 \uc804\ub2ec\ub418\uc5c8\uc2b5\ub2c8\ub2e4.');");
	writer.println("location.href='websmsform.jsp';");
	writer.println("</script>");
	writer.flush();
	return;
} // end of check all of validation 
else {
	if (strIsInsa.equals("N")) { //\uc778\uc0ac\uc5f0\ub3d9\uc548\ud560\ub54c
		
	}else{ //\uc778\uc0ac\uc815\ubcf4 \uc5f0\ub3d9 \ud560\ub54c
	}

}

//SMS\uc778\uc99d\ubc88\ud638 \ub9cc\ub4e4\uae30
String certkey = "000000";

int RandNum = (int)(Math.random()*1000000 + 1);
DecimalFormat dt = new DecimalFormat("000000");
certkey = dt.format(RandNum);

String SND_MSG ="KEPCO-SSO \uc778\uc99d\uc11c\ubc1c\uae09\uc6a9 : \uc778\uc99d\ubc88\ud638 ["+ certkey + "]\uc744(\ub97c) \uc785\ub825\ud558\uc2ed\uc2dc\uc624";



int cnt_user = 0 ; // \uc0ac\ubc88\uc5d0 \ud574\ub2f9\ud558\ub294 \uc0ac\uc6a9\uc790 \uc874\uc7ac \uc720\ubb34(0:\uc5c6\uc74c, \uadf8\uc678 \uc874\uc7ac)

int phoneLen = 0 ;


if (strIsInsa.equals("Y")) { //\uc778\uc0ac\uc815\ubcf4 \uc5f0\ub3d9\uc2dc
	//\uc0ac\ubc88\uc774 \ub118\uc5b4\uc624\uba74 \uc778\uc0ac\ucabd\uc5d0\uc11c \ud574\ub2f9 \uc0ac\ubc88\uc758 \uc804\ud654\ubc88\ud638\ub97c \uac00\uc9c0\uace0 \uc624\uc790
	Context ic = new InitialContext();
	DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/INSA");
	ResultSet rs = null;

	Connection conn = null;
	Statement stmt = null;

	try{
		//\uc0ac\ubc88\uc774 \uc778\uc0ac\uc815\ubcf4\uc5d0 \uc874\uc7ac\ud558\ub294\uc9c0 \uccb4\ud06c
		conn = ds.getConnection();
		//Creat Query and get results
		stmt = conn.createStatement();
		rs = stmt.executeQuery("SELECT COUNT(*) as cnt FROM IRIS.V_INSA WHERE EMPNO ='"+ empno +"'");
		while (rs.next()){
			cnt_user = rs.getInt("cnt");
		}
		if (cnt_user == 0){
			response.setCharacterEncoding("EUC-KR");
			PrintWriter writer = response.getWriter();
			writer.println("<script type='text/javascript'>");
			writer.println("alert('\uc785\ub825\ud558\uc2e0 \uc0ac\ubc88("+ empno +")\uc5d0 \ub300\ud55c \uc815\ubcf4\uac00 \uc778\uc0ac\uc815\ubcf4\uc5d0\ub294 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.');");
			writer.println("window.close();");
			writer.println("</script>");
			writer.flush();
			return;
		}else{ // \uc0ac\uc6a9\uc790 \uc815\ubcf4 \uc874\uc7ac\ud560\ub54c
			rs = stmt.executeQuery("SELECT EMPNO, NAME AS USER_NAME, CELLNO FROM IRIS.V_INSA WHERE empno ='"+ empno +"'");
			
			while (rs.next()){
				userName = rs.getString("USER_NAME");
				phone = rs.getString("CELLNO");
				phoneLen = phone.length();
			}
		}
	}
	catch(Exception ex){
		ex.printStackTrace();
	} finally {
		rs.close();
		stmt.close();
		conn.close();
	}
}else{ //\uc778\uc0ac\uc815\ubcf4 \uc5f0\ub3d9 \uc548\ud560\ub54c
	cnt_user = 1 ;
	phoneLen = 13;
	userName = "\uac1c\ubc1c\uc790";
}
		


if (cnt_user > 0 ) { //\uc0ac\uc6a9\uc790 \uc815\ubcf4\uac00 \uc874\uc7ac\ud55c\ub2e4\uba74 \uc778\uc99d\ud3fc\ubcf4\uc5ec\uc8fc\uc790

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
if (strIsInsa.equals("N")) {

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((SND_MSG));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
}	

    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((certkey));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    
}//\uc0ac\uc6a9\uc790 \uc815\ubcf4 \uc874\uc7ac ..end

  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1257324557874484737L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("websmssend.jsp"), 2318703079189083043L, true);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  static {
    _jsp_string5 = "\";\r\nopener.readForm.sms.style.background=\"#ffffff\";\r\nopener.readForm.sms.disabled=false;\r\nopener.setTimerOn();\r\nwindow.close();\r\n\r\n</script>\r\n\r\n<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n</body>\r\n</html>\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\nalert(\"".toCharArray();
    _jsp_string3 = "\");\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n<head>\r\n<title>SMS \uc778\uc99d\ud558\uae30</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n</head>\r\n<script language=\"javascript\">\r\n".toCharArray();
    _jsp_string4 = "\r\nopener.readForm.smschk.value=\"".toCharArray();
  }
}
